module.exports = {
  TEST_MARKET: 'San Francisco',
  NUM_TOTAL_LISTINGS: 5,
  SINGLE_AVAILABILITY_DATE: '2017-11-12',
  NUM_SINGLE_AVAILABILITY_LISTINGS: 4,
  NO_LISTINGS_MARKET: 'Timbuctoo',
  NO_AVAILABILITY_DATE: '2017-10-02',
  LIMIT: 2,
};
