const AVAILABILITY_YEAR_MONTH = '2018-03';
const SINGLE_AVAILABILITY_DATE = '26';
const NO_AVAILABILITY_DATE = '12';
const AVAILABLE_DATE_RANGE_START = '19';
const AVAILABLE_DATE_RANGE_END = '23';

module.exports = {
  TEST_MARKET: 'San Francisco',
  NO_LISTINGS_MARKET: 'Timbuctoo',

  NUM_TOTAL_LISTINGS: 5,
  NUM_SINGLE_AVAILABILITY_LISTINGS: 4,
  LIMIT: 2,

  SINGLE_AVAILABILITY_DATE: `${AVAILABILITY_YEAR_MONTH}-${SINGLE_AVAILABILITY_DATE}`,
  NO_AVAILABILITY_DATE: `${AVAILABILITY_YEAR_MONTH}-${NO_AVAILABILITY_DATE}`,
};
